CREATE TABLE IF NOT EXISTS iowa_liquor_sales (
    invoice_line_no TEXT PRIMARY KEY,
    date TIMESTAMP,
    store TEXT,
    name TEXT,
    address TEXT,
    city TEXT,
    zipcode TEXT,
    store_location TEXT,
    county_number TEXT,
    county TEXT,
    category TEXT,
    category_name TEXT,
    vendor_no TEXT,
    vendor_name TEXT,
    itemno TEXT,
    im_desc TEXT,
    pack INTEGER,
    bottle_volume_ml INTEGER,
    state_bottle_cost NUMERIC,
    state_bottle_retail NUMERIC,
    sale_bottles INTEGER,
    sale_dollars NUMERIC,
    sale_liters NUMERIC,
    sale_gallons NUMERIC
);
